version: '3.8'
services:
  booking-svc:
    image: magnusov/taxabookingservice:latest
    environment:
      - WorkPath=/srv/plan
    depends_on:
      - rabbit
    restart: on-failure
    ports:
      - "5001:80"
    networks:
      - default
    volumes:
      - plan:/srv/plan

  plan-svc:
    image: magnusov/planservice:latest
    environment:
      - WorkPath=/srv/plan
      - MqHost=rabbitmq
      - ConnectionString=PLACEHOLDER
      - DatabaseName=Maintenance
    depends_on:
      - rabbit
      - plan-db
    restart: on-failure
    ports:
      - "5002:80"
    networks:
      - default
    volumes:
      - plan:/srv/plan

  maintenance-svc:
    image: magnusov/maintenanceservice:latest
    environment:
      - MqHost=rabbitmq

  plan-db:
  image: mongo:latest
  container_name: maintenance-db
  environment:
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: 1234
  ports:
    - "27100:27100"
  volumes:
    - mongodb_data_container:/data/db

  rabbit:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - default

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - booking-svc
      - plan-svc
    ports:
    - "4000:4000"
    networks:
      - default

volumes:
  plan:
    external: false

networks:
  default:
    driver: bridge
    name: projekt