version: '3.8'
services:
  upload-svc:
    image: magnusov/taxabookingservice:latest
    environment:
      - WorkPath=/srv/plan
    depends_on:
      - rabbit
    restart: on-failure
    ports:
      - "5001:80"
    networks:
      - default
    volumes:
      - plan:/srv/plan

  list-svc:
    #image: browndahl/plan-service:latest
    image: planservice
    environment:
      - WorkPath=/srv/plan
      - MqHost=rabbitmq
    depends_on:
      - rabbit
    restart: on-failure
    ports:
      - "5002:80"
    networks:
      - default
    volumes:
      - plan:/srv/plan

  rabbit:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default

volumes:
  plan:
    external: false

networks:
  default:
    driver: bridge
    name: projekt
